SKYLINE_GIT_STATUS_UNTRACKED="${SKYLINE_GIT_STATUS_UNTRACKED="?"}" # nf-fa-question_circle
SKYLINE_GIT_STATUS_ADDED="${SKYLINE_GIT_STATUS_ADDED="+"}" # nf-fa-plus_circle
SKYLINE_GIT_STATUS_MODIFIED="${SKYLINE_GIT_STATUS_MODIFIED="!"}" # nf-fa-exclamation_circle
SKYLINE_GIT_STATUS_RENAMED="${SKYLINE_GIT_STATUS_RENAMED="»"}" # nf-fa-arrow_circle_righ
SKYLINE_GIT_STATUS_DELETED="${SKYLINE_GIT_STATUS_DELETED="✘"}" #nf-fa-times_circle
SKYLINE_GIT_STATUS_STASHED="${SKYLINE_GIT_STATUS_STASHED="$"}" 
SKYLINE_GIT_STATUS_UNMERGED="${SKYLINE_GIT_STATUS_UNMERGED="="}"
SKYLINE_GIT_STATUS_AHEAD="${SKYLINE_GIT_STATUS_AHEAD="⇡"}"
SKYLINE_GIT_STATUS_BEHIND="${SKYLINE_GIT_STATUS_BEHIND="⇣"}"
SKYLINE_GIT_STATUS_DIVERGED="${SKYLINE_GIT_STATUS_DIVERGED="⇕"}"

skyline::git() {
  source "$SKYLINE_ROOT/section/git-branch.zsh"
  
  skyline::git_branch
}